### ISSUE TITLE
Delete a account 

### ISSUE THREAD

**Issue by rwobben** [rwobben/paytime#15]
For deleting a account, we have to ask the user which account he/she wants to delete. 

So accounts looks like this [ { "test", 100, [] } , {"test2, 80,0] } 

Lets say the user enters test1 as the account that has to be deleted. 
How can I tell haskell to check if a account is in the accounts map so I can make a message that the acccount is deleted or that the account cannot be deleted because it does not exist.

**Comment by GetContented** [comment]
Ok so that sounds like you want to use the name as the identifier.

Break it into two parts.

Firstly, there's the part for the User Interface. This will work best if it presents the user with a question something like "here is a list of the account names. Type the one you want to delete."

Then, you check that the account is in the list of account names. Let's assume you have that function: `indexOfAccountNamed :: String -> Maybe Int` which will take an account name, and return a Maybe Int, whose value can be either the index as an Int wrapped in Just, or the value Nothing.

So, the check to see if the account is in the list is something like `case indexOfAccountNamed accountName of  Nothing -> do { putStrLn "No such account name"; return accounts } ; Just index -> return (deleteAccountAtIndex accounts index)`

Does that make sense?

**Comment by rwobben** [comment]
it make sense. 
When I try to do this in parts so I can see how it works I see this message : 

    /home/ubuntu/workspace/paytime/paytime/src/Lib.hs:52:58:
        Couldn't match type ‘Account’ with ‘[Char]’
        Expected type: [String]
          Actual type: [Account]
        In the second argument of ‘elemIndex’, namely ‘accounts’
        In the expression: elemIndex account accounts

with this as code :  

    doDeleteAccounts :: [Account] -> IO [Account] 
    doDeleteAccounts accounts = do
      putStrLn "which account to do want to remove"
      deleteAccount <- getLine
      print $ indexOfAccountNamed deleteAccount accounts
      return [] 
 
    indexOfAccountNamed :: String -> [Account] -> Maybe Int   
    indexOfAccountNamed account accounts = elemIndex account accounts  

it seems that elemIndex only works on strings :( 

Roelof
 

doDeleteAccounts :: [Account] -> IO [Account] 
doDeleteAccounts accounts = do
  putStrLn "which account to do want to remove"
  deleteAccount <- getLine
  ???
  return [] 
 
indexOfAccountNamed :: String -> [Account] -> Maybe Int   
indexOfAccountNamed account accounts = elemIndex account accounts

**Comment by rwobben** [comment]
I wonder if im on the right track with first testing and then deleting. 
Maybe  a idea to use a filter ??

**Comment by rwobben** [comment]
I did try filter like this : 

   filter (\account -> accountName account /= deleteAccount) accounts

but then I see this error messsage : 

    /home/ubuntu/workspace/paytime/paytime/src/Lib.hs:48:3:
        Couldn't match expected type ‘IO a0’ with actual type ‘[Account]’
           In a stmt of a 'do' block:
          filter (\ account -> accountName account /= deleteAccount) accounts
        In the expression:
          do { putStrLn "which account to do want to remove";
               deleteAccount <- getLine;
               filter
                 (\ account -> accountName account /= deleteAccount) accounts;
               return [] }

So I really need your help on this. IM stuck

**Comment by GetContented** [comment]
No, elemIndex works on any type, but you're using it incorrectly by passing a String in to find within an Account List, which won't work. Its type is Eq a => a -> [a] -> Maybe Int. Notice that it expects a and [a] both have the a in them - that means they MUST be the same type as each other. That means if you are looking for a String, it'll expect a [String] as the second argument. Make sense? elemIndex finds the index of an element when you pass it an element, but you probably want a function that takes a predicate (predicate means testing function), and a list, and returns a single element. its type would be something like (a -> Bool) -> [a] -> a. This may be a really good exercise to try.

Anyway, Filter is an *excellent* idea. Much better than the idea of finding the index then removing that index. Well done! Higher order functions for the win. :) Filter takes a predicate and a list and returns a list where all items are true when the predicate is called on them. (a -> Bool) -> [a] -> [a]. Good choice.

Okay, so the filter function is a pure function that deals only with pure values. Because we're doing it within a monadic context, all "statements" inside a do block MUST result in a monadic value - a value of the monad we're inside. In our case, that's the IO Monad, and so the type must be some kind of an IO type.

There are TWO exceptions to this... one is using monadic let syntax (which is different than a let...in expression), and the other is using  <- which will set the name on the left to the unwrapped-monadic-value of the expression on the right.

We actually want to just get filtered value... so we can use "let" to give ourselves a kind of temporary variable that we can use in other places after the let statement. You can see how I've done that in other code, then you can use return to wrapper that value in IO where we're currently saying return [].

"return" does not do what it does in other languages. All it does is turn a regular value into a monadic value. So, because we're in IO, saying return [] results in an IO []. The fact that it's the last thing in the do block means it's the value that is the result of the expression, NOT the fact that it has return before it. I hope that's clear. This often confuses people.

So, the lesson here is... use monadic let expressions to set "temporary values" when not using the monad you're inside, and use <- to set "temporary values" by pulling a value out of a monadic context (which is what we do when we say deleteAccount <- getLine : we're actually pulling the string out of the IO String typed value (this is the type of getLine) and defining deleteAccount to be the result of that. We can only do that because the do block is actually INSIDE the IO monadic value itself.

The rest of the lesson is... when you need to, use "return" to wrap an expression in the monad... and every other statement (ie every other line of the do block) must result in an IO-wrapped value. As an example, putStrLn is a function that takes a string, and provides an IO () value, so you can put that on a line normally. getLine is an IO action that takes no values and returns an IO String value, so that is fine, too (but fairly useless unless you use <- with it to pull the value out and set it to a variable).

Hope this is clear, as usual ask if not.

**Comment by rwobben** [comment]
Oke, 

I try the exercise to use elemindex. I have to think good how I can make the predicate then,

You mean by the other code the code we have used to add a account ? 
Then I hope and think I can solve it.

**Comment by rwobben** [comment]
Sorry, still stuck. 

I tried this : 

    doDeleteAccounts :: [Account] -> Maybe [Account] 
    doDeleteAccounts accounts = do
      putStrLn "which account to do want to remove"
      deleteAccount <- getLine
      find (deleteAccount == accountName accounts) accounts 

and still a lot of error messages.

**Comment by rwobben** [comment]
This monad stuff is difficult. Maybe look for a way to make it work with just function parameters instead of inputting things ?

**Comment by GetContented** [comment]
Yeah, this is why I tried to make sure you didn't do too much too soon.

It's actually not hard at all, it's just that there are about 12 things you have to learn before you will understand how it all works :)

... This is why I was going to get you to do the pure functions and I'd do the main loop... though the monadic bit is the "exciting bit".

**Comment by GetContented** [comment]
doDeleteAccounts has the wrong type... you've set it up to be in the *Maybe* monad, but it need to be in the IO monad.

(ie [Account] -> IO [Account], not [Account] -> Maybe [Account]).

**Comment by rwobben** [comment]
I know,
I try to find out how I can display the outcome of the find command. 
As I understand you right I could use return to "convert" the outcome of the find command to a IO() 
but still no luck.

**Comment by GetContented** [comment]
Well doDeleteAccounts should return the new accounts list... so you want an expression that gives you the new accounts list... 

you can use a case expression, because it will let you pattern match on the Maybe Int value that's returned by find.

let newAccounts = case (find...) of Nothing -> accounts ; Just idx -> (take idx accounts) ++ (drop (idx + 1) accounts)
return newAccounts

something like that should work ok.

**Comment by GetContented** [comment]
By the way, it makes no sense at all to "convert find's result to IO ()"... that's why you need a let expression. You will use a let for any time you just want a value that ISN'T inside the monad that you're in.... Maybe Int is obviously NOT in the IO monad...

**Comment by GetContented** [comment]
It's silly you trying to do this stuff when you don't know how to do it.

Either I should be doing it, or we should get you to the point where you know how to do it.

To use Monad, you need to understand typeclasses and algebraic types very well, and you'll encounter recursion so it'd be good to be very familiar with that. 

I think it's out of order to get you to do monadic stuff now.

**Comment by GetContented** [comment]
that find function call and whatnot would be better off as a pure function separated from the doDeleteAccount function, I think...

**Comment by rwobben** [comment]
I know but I cannot make it work that I can see the output of the find function 
Or can I use the print statement for that ?

**Comment by rwobben** [comment]
I have now this : 

    doDeleteAccounts :: [Account] -> IO [Account] 
    doDeleteAccounts accounts = do 
      putStrLn "which account to do want to remove"
      deleteAccount <- getLine
      let newAccounts = case (find_index deleteAccount accounts)  of Nothing -> accounts ; Just idx -> (take idx accounts) ++ (drop (idx + 1) accounts)
      return newAccounts

    find_index :: String -> [Account] -> String 
    find_index search_string search_map = find (search_string == accountName search_map) search_map

But still a lot of error messages . See http://lpaste.net/148599

So I get the feeling that deleting things are more then I can chew.

**Comment by GetContented** [comment]
The problem, as always, is you're trying to do everything at once.

You're trying to create a doDeleteAccounts function while also learning about how to find an item in a list while also writing the function to remove an item from the list, while also tackling the do syntax of Monads.

**Comment by GetContented** [comment]
Let's go back to something that works...
    doDeleteAccounts :: [Account] -> IO [Account] 
    doDeleteAccounts accounts = do 
      putStrLn "Which account to do want to remove?"
      accountNameToDelet <- getLine
      return accounts

**Comment by rwobben** [comment]
oke,

I did not try to do everything at once . Maybe it looks that way.
I did  managed to make the part we have to work. Except I was forgetting the return 

What I tried the last 2 days was the part how to find a item in a list.
For debugging purposes  I like to see the output of the find command. 

The deleting part I did not try it yet.  First I want to be sure that I could find the item I want to delete.

**Comment by GetContented** [comment]
Ok. I'm not sure how you ended up with broken code then. You just need to match the types up.

**Comment by rwobben** [comment]
but your code does not work. 
When I try it I see this error messages.,

    /home/ubuntu/workspace/paytime/paytime/src/Lib.hs:45:21:
        Illegal type signature: ‘[Account]
                                 -> IO [Account] doDeleteAccounts accounts’
          Perhaps you intended to use ScopedTypeVariables
        In a pattern type-signature

    /home/ubuntu/workspace/paytime/paytime/src/Lib.hs:49:9:
        Not in scope: ‘accounts’
        Perhaps you meant data constructor ‘Account’ (line 8)

**Comment by GetContented** [comment]
So, once we have that, we need to work out how to remove the account with that name, if there is one... 

So you need "some function" which takes a list of accounts, and removes one named something... we can "black box" this for the doDeleteAccount function:

    doDeleteAccounts :: [Account] -> IO [Account] 
    doDeleteAccounts accounts = do 
      putStrLn "Which account to do want to remove?"
      accountNameToDelete <- getLine
      let newAccounts = removeAccountNamed accountNameToDelete accounts
      return newAccounts

    removeAccountNamed :: String -> [Account] -> [Account]
    removeAccountNamed s accts = accts

Note that removeAccountNamed doesn't actually do anything yet... it just passes back the account list it got, but we are only doing ONE thing at once.

**Comment by rwobben** [comment]
oke, this part I understand

**Comment by GetContented** [comment]
Um... if you're going to send me errors, I need to see what code you're running as well, otherwise I can't debug the code you're running.

**Comment by GetContented** [comment]
Ok... good. So at this point we can work on removeAccountNamed.

**Comment by rwobben** [comment]
It was a typo of me.  So we can continue. Sorry for the noise

**Comment by GetContented** [comment]
It's fine. It's my aim to make this stuff so you can understand it. I don't want you frustrated :)

**Comment by GetContented** [comment]
So we can look at this function you were using...elemIndex :: Eq a => a -> [a] -> Maybe Int

**Comment by GetContented** [comment]
But maybe what we want is something that takes a predicate and finds an item based on that instead... so you found the find function, too... find :: Foldable t => (a -> Bool) -> t a -> Maybe a

That's a much better fit. It takes a function from "a" to Bool then a "t a" (which we can think of as [a] because our Foldable t is a List), and returns an "a" wrapped in a Maybe. Sweet :)

**Comment by rwobben** [comment]
oke, It takes a something and a array of the same type  and it returns a just int or Nothing

**Comment by GetContented** [comment]
A list, not an array. Haskell has Arrays, and we're not using them here.

**Comment by GetContented** [comment]
I know what you meant tho.

**Comment by rwobben** [comment]
oke, I get confused by names. One language names it a list other a array 
So we want to use find. 
Then we have to find a way to compare AccountToBeDeleted with all the names of accounts. Right ?

**Comment by GetContented** [comment]
so we can think of this... find :: Foldable t => (a -> Bool) -> t a -> Maybe a

as this:

       find :: (Account -> Bool) -> [Account] -> Maybe Account

and we can write a function that is Account -> Bool pretty easily:

    isAccount :: String -> Account -> Bool
    isAccount name acct = accountName acct == name

Now if we pass this function a String, it'll have the right type... for example:

     isAccount "Joe" :: Account -> Bool

**Comment by GetContented** [comment]
Are you with me to here?

**Comment by rwobben** [comment]
yes.

**Comment by GetContented** [comment]
So now we need a function to find the index, and another to remove an index.

**Comment by GetContented** [comment]
or we can just use filter. Either is fine. We'll do both.

**Comment by rwobben** [comment]
yes, two seperate parts

**Comment by rwobben** [comment]
I take a break. Be back in 2 hours

**Comment by GetContented** [comment]
I haven't tested this, but this is one way to do it:

    doDeleteAccounts :: [Account] -> IO [Account] 
    doDeleteAccounts accounts = do 
      putStrLn "Which account to do want to remove?"
      accountNameToDelete <- getLine
      let newAccounts = removeAccountNamed accountNameToDelete accounts
      return newAccounts

    isAccount :: String -> Account -> Bool
    isAccount name acct = accountName acct == name
    
    removeAccountNamed :: String -> [Account] -> [Account]
    removeAccountNamed s accts = acctsAfter
      where maybeIndex = findIndex (isAccount s) accts
            acctsAfter = case maybeIndex of
                         Nothing  -> accts
                         Just idx -> (take idx accts) ++ (drop (idx + 1) accts)

**Comment by GetContented** [comment]
ok... no worries.

And the one with filter is a lot easier.

**Comment by GetContented** [comment]
But... I did this by steps... constantly black boxing what I needed until I got to the bottom.

So I needed a function to find the index of something using a predicate, found the findIndex function, then I needed a function that would return a list that has had a particular index removed. There *may* actually already be a function in Data.List that does this. We could just use that... but I wrote my own.

**Comment by GetContented** [comment]
No, Lists are almost always singly linked lists, and arrays are not. They are different things. They are similar looking, but Array is more efficient for indexing. Clojure has List and Vector. These are not array. Vector is not an array or list. They're all different things. Ruby Array are arrays, not Lists or vectors.

**Comment by rwobben** [comment]
Thanks, 

I have tested it and it works. 
I think my problem is and maybe it's what you tried to say is that I try to put everything in one function where I schould have used several. 

Up to the next one in your list of making a main function

**Comment by rwobben** [comment]
Chips, I forgot that we also were making a filter one.

My first try : 

    doDeleteAccounts2 :: [Account] -> IO [Account] 
    doDeleteAccounts2 accounts = do 
      putStrLn "Which account to do want to remove?"
      accountNameToDelete <- getLine
      let newAccounts = removeAccountNamed2 accountNameToDelete accounts
      return newAccounts

    isNotAccount :: String -> Account -> Bool
    isNotAccount name acct = accountName acct /= name

    removeAccountNamed2 :: String -> [Account] -> [Account]
    removeAccountNamed2 s accts  = filter (isNotAccount s accts) accts

but is has errors : 

    /home/ubuntu/workspace/paytime/paytime/src/Lib.hs:76:40:
        Couldn't match expected type ‘Account -> Bool’
                    with actual type ‘Bool’
        Possible cause: ‘isNotAccount’ is applied to too many arguments
        In the first argument of ‘filter’, namely ‘(isNotAccount s accts)’
        In the expression: filter (isNotAccount s accts) accts

    /home/ubuntu/workspace/paytime/paytime/src/Lib.hs:76:55:
        Couldn't match expected type ‘Account’ with actual type ‘[Account]’
        In the second argument of ‘isNotAccount’, namely ‘accts’
        In the first argument of ‘filter’, namely ‘(isNotAccount s accts)’

**Comment by GetContented** [comment]
You're trying to do too many things at once. You need to do ONE SINGLE PIECE at a time. Not one single function. One single tiny piece of a function. Each time you add a single piece, or do a single piece, checking the types at each step, you should run your code again. The typechecker will tell you at that point if you've made a mistake. If you have, Look at the last thing you wrote and think why it might be a mistake. Revert your code to the step before, then look at the type of whatever you're adding or changing and make sure it matches. If the typechecker is telling you there's an error you know only that one last piece can be a mistake.

Do you work in GHCi?

If so, are you aware of the :t (or :type) command? If you give it an expression, it will tell you the type of that expression.

for example, just now I did this:

    *Lib2> :t filter
    filter :: (a -> Bool) -> [a] -> [a]

I'm now going to run through what I do with you step by step.

**Comment by GetContented** [comment]
First, I make a "stupid" function that just returns any value that will work.

In this case, that's just return on accuonts which will wrap accounts in the IO monad

    doDeleteAccounts2 :: [Account] -> IO [Account]
    doDeleteAccounts2 accounts = return accounts

Now I run that in GHCi by doing :r. It compiles, so I'm happy.

Next, I think about what we're doing. Ok, so we want to:
1. Ask the user an account name
2. Remove the account if it exists
3. Return the list of accounts (changed or unchanged)

Next I think about the first point and see if it's as small as it can be. I think this is, it's just one function application... however, the doDeleteAccounts2 needs to be in a do block rather than just a simple return statement, and I like to MAKE SURE i don't make mistakes, so I'll just put a do block in there and reload with :r - this is completely unnecessary and quite stupid, but good to do at the beginning to 100% make sure it's right.

    doDeleteAccounts2 :: [Account] -> IO [Account]
    doDeleteAccounts2 accounts = do
                                  return accounts

Next, I do the minimum amount to make sure the code still runs and introduce the FIRST step above. Note that in a do block for an IO monadic value, every line MUST be an IO value unless it's using one of these: (let or <-). putStrLn has type String -> IO () and we're applying a string to it, so the expression will be of type IO () which is perfect:

    doDeleteAccounts2 :: [Account] -> IO [Account]
    doDeleteAccounts2 accounts = do
                                  putStrLn "Please enter an account name to delete?"
                                  return accounts

Reload again, just to make sure. It compiles. Great. :)
Next, Look at Step 2 above. It seems I missed a step... to take the account name value as a named variable. I'll amend the list:
1. Ask the user an account name
2. Retrieve the account name and store it in a variable called acctName
3. Remove the account if it exists
4. Return the list of accounts (changed or unchanged)

So let's think how to do this new step 2... well it's one single step, and it's just going to be using <- :

    doDeleteAccounts2 :: [Account] -> IO [Account]
    doDeleteAccounts2 accounts = do
                                  putStrLn "Please enter an account name to delete?"
                                  acctName <- getLine
                                  return accounts

Ok :r and it compiles fine. Great.
Next, we look at step 3. This is a big step. It could be broken into smaller pieces, but if I think about it, it's a pure function... (that means it doesn't actually have anything to do with IO... the function type would be something like String -> [Account] -> [Account] and so we can adjust our to do list accordingly, by expanding point 3 into more points:

1. Ask the user an account name
2. Retrieve the account name and store it in a variable called acctName
3. Remove the account if it exists
3. a) write a dummy function called deleteAccount :: String -> [Account] -> [Account]
3. b) adjust the code to doDeleteAccounts2 so that we define a newAccounts variable which is set to the result of deleteAccount, and make doDeleteAccounts2 return that value.
3. c) finish writing deleteAccount properly
4. Return the list of accounts (changed or unchanged)

Ok so now that's done, we do 3. a) and write the dummy function. This will literally just pass back the passed in List.

    deleteAccount :: String -> [Account] -> [Account]
    deleteAccount s accts = accts
    
then I save and :r at GHCi, and it compiles, so I'm happy.

Next, we want to do 3. b)... that involves two line adjustments to doDeleteAccounts2. First one:

    doDeleteAccounts2 :: [Account] -> IO [Account]
    doDeleteAccounts2 accounts = do
                                  putStrLn "Please enter an account name to delete?"
                                  acctName <- getLine
                                  let newAccounts = deleteAccount acctName accounts
                                  return accounts

...which is the addition of a let statement... newAccounts will be our accounts after we've deleted one. Obviously we'll aso need to make sure that THAT is the new final value of this monadic expression. But first, save and :r, and it compiles so we're good.

Next change, the return expression at the end of the do block need adjusting to newAccounts rather than accounts:

    doDeleteAccounts2 :: [Account] -> IO [Account]
    doDeleteAccounts2 accounts = do
                                  putStrLn "Please enter an account name to delete?"
                                  acctName <- getLine
                                  let newAccounts = deleteAccount acctName accounts
                                  return newAccounts

    deleteAccount :: String -> [Account] -> [Account]
    deleteAccount s accts = accts
    
saves and :r, and we're still good.

Ok... that was 3. b), so now we need to do 3. c) which is to flesh out our dummy deleteAccount function so that it actually works. The typechecker won't help us much here to determine if we're removing the right one (a test might be handy at this point), but it *will* help us to make sure our code still compiles.

This may involve many steps. First thing I will do is think about what I want to happen. So we're given the name (as s), and the accounts list (as accts), and we want to use filter to make sure only ones that are NOT named that are allowed through.

So I go to GHCi, and type :t filter to check the type signature. It gives me this:

    *Lib> :t filter
    filter :: (a -> Bool) -> [a] -> [a]

So filter takes a function from a to Bool. Our "a" is Account, so we want a function that goes from Acct -> Bool and what should it test for? It should test to see if the name is not "s" from our deleteAccount function. filter takes TWO arguments though and the second one has to be a [a], which means (for us, here) [Account]... so first we write the function Acct -> Bool that tests if the name is not s. This is that function as an anonymous function, and i'll use a where clause to give it a name: (\acct -> accountName \= s):

    deleteAccount :: String -> [Account] -> [Account]
    deleteAccount s accts = accts
      where notNamed = \acct -> accountName \= s

And save and :r and you probably realised that there's a bug:

        Not in scope: ‘\=’
        Perhaps you meant one of these:
          ‘/=’ (imported from Prelude), ‘<=’ (imported from Prelude),
          ‘>=’ (imported from Prelude)
    Failed, modules loaded: none.

What does that mean? It means \= was not found... the reason? it's not a function. It should be /= so I make the change and test again:

    deleteAccount :: String -> [Account] -> [Account]
    deleteAccount s accts = accts
      where notNamed = \acct -> accountName /= s

Now this doesn't work still... because there's another bug:

      Couldn't match type ‘[Char]’ with ‘Account -> String’
      Expected type: Account -> String
        Actual type: String
      In the second argument of ‘(/=)’, namely ‘s’
      In the expression: accountName /= s

Which if I look again at what I've written, I missed out a reference to acct... so I'll go and add that:

    deleteAccount :: String -> [Account] -> [Account]
    deleteAccount s accts = accts
      where notNamed = \acct -> accountName acct /= s

This time it compiles. You notice I've named an anonymous function (a lambda) by doing this. That's a little weird, so let's "refactor" it to use a normal function rather than an anonymous one:

    deleteAccount :: String -> [Account] -> [Account]
    deleteAccount s accts = accts
      where notNamed acct = accountName acct /= s

Ok, so I reload and this compiles again as expected with no problems.

But we aren't yet finished with 3. c) because all I've done is add a function to the where clause, I'm not actually using it, so the next step is to make it use it... so I introduce the filter application:

    deleteAccount :: String -> [Account] -> [Account]
    deleteAccount s accts = filter notNamed accts
      where notNamed acct = accountName acct /= s

Of course, I reload, and it works. So that's 3. c) done.

Now, I look back ad my list, and 4. is alerady done (we did it in another step). So that's it. Done :)

I know this seems like a lot, but it's MUCH faster when you're just doing it and not reading it... it's a very quick process, and you catch your errors very quickly... no need to run the code, just to recompile it and it takes 1/4 of a second each time between steps. When you get more confident, you'll be able to skip steps, maybe do 2 or 3 at a time. At my level, I can write out whole functions because I'm so used to doing all the steps in my head, and I've seen all the errors so it's easier to spot what went wrong.

**Comment by GetContented** [comment]
(Sorry, markdown automatically numbered my points...I'll tro to correct it)

**Comment by rwobben** [comment]
No problem. If it's no problem I close this one.

**Comment by GetContented** [comment]
Yeah, tha'ts fine. Did you follow my step-by-step process?

**Comment by rwobben** [comment]
Nope, I will try it with the following issue

**Comment by GetContented** [comment]
Ok. The best way to learn (in my opinion), is to take a small function like this that you've seen. Read it. Understand how it works to the best of your ability. Then rebuild it without referring to the completed one. Start from scratch in a new file or section of the file so that you can't see the original one, then do the steps. If you have to look, so be it, but mark down on a piece of paper how many times you had to look. Do this again and again until you don't have to look.

Of course doing it with ONE example will get boring pretty quick, but if you do this at least once for every example we do, you'll quickly become very very good at programming, and ask very relevant questions.
