### ISSUE TITLE
Convert accounts from a list to a map 

### ISSUE THREAD

**Issue by rwobben** [rwobben/paytime#18]
Because we want to use as much existing functions as possible and updating a map is easier then updating a list, I think accounts schould be a map instead of a list.

**Comment by GetContented** [comment]
Data.Map is a module in the containers package.

**Comment by rwobben** [comment]
yep, that I already found out. 
Together with Data.insert we can insert new accounts and with Data.update we can update accounts

**Comment by GetContented** [comment]
Yep! :) cool :) Maps are very nice things.

**Comment by rwobben** [comment]
oke, 

Can we function by function change the code then ?

**Comment by GetContented** [comment]
The best way to approach this so we don't end up in a mess is to add a new function proxying the functionality we're currenly using that depends on the shape of the list and then we'll only have at most one or two places to change when we shift over to Map.

**Comment by rwobben** [comment]
oke,  If that is the best way we do it. 
I thought more about rewriting everything piece by piece.
I know that some functions will not work temporarly but that for me is no problem.

**Comment by GetContented** [comment]
It can be a problem if things break and you can't work out why. This is a surefire way to get confused and into problems where you can't fix them... especially as Map is *quite* different than list and you've never used it before.

**Comment by GetContented** [comment]
I think we should finish the deposit functionality first, shouldn't we?

**Comment by rwobben** [comment]
We can do that 

We do not want a sure way to get confused.  but the way you suggested look a way that we are still using list but also not.  It looks like a dirty way to solve it , not the right way

**Comment by GetContented** [comment]
It's not dirty at all.

I'm suggesting we put a piece of indirection in. This is a refactoring pattern where we're abstracting out the implementation detail from our functions. They shouldn't rely on the the implementation details of how accounts are stored.

This is in no way dirty, or messy. It's the opposite. It removes dependencies.

**Comment by rwobben** [comment]
oke, 

Then we take this road. 
First this or first make deposit work ?

**Comment by GetContented** [comment]
It's up to you. You mentioned a while ago that you only want to work on one thing at once, so I'm just suggesting what I thought you'd prefer.

**Comment by rwobben** [comment]
oke, what is the first step to make this work ?

**Comment by GetContented** [comment]
Haha okay here we go! :)

We're going to change the type of our accounts store from [Account] to Map String Account.
Map String Account is a map whose keys are String and whose values are Account.

To do this, we'll first refactor [Account] to a type synonym called Accounts. This means creating a type synonym type Accounts = [Account] and then going through and finding every reference of [Account] and changing it to Accounts. We'll do this because it'll let us change ALL those types at one point, by adjusting that synonym later.

Once this is done, we will need to look through all the code and find all the parts that rely on accounts being a list, and pulling out a function for each of those places (not changing the code, but making sure we've extracted all List-relating code into one place so we know exactly what we need to change in one place).

Then, we'll just need to change all that code to be its equivalent Map code rather than List code.

Does all this make sense?

**Comment by rwobben** [comment]
oke, this makes sense. 

And later on we are going to change the list functions to map functions.

**Comment by GetContented** [comment]
I don't see a PR, but if it has

    type Accounts = [Account]

Then I'm happy with it :-) It's a pretty quick and easy change.

**Comment by rwobben** [comment]
Sorry: I forget to make a PR. 
I did that and change every [Account] to Accounts. 
it compiles well.

**Comment by GetContented** [comment]
Cool. Yep. PR looks good.

**Comment by GetContented** [comment]
Ok so I had a bit of a look, and there aren't many places where we're relying on accounts being a list.

doCreateAccounts and doDepositAccounts are the only main function that relies on it being a list. The others are pure auxiliary functions: accountsAfterDeposit (which we should pull the list stuff out into a separate function), deleteAccount , removeAccountNamed.

**Comment by GetContented** [comment]
So the next step would be to extract the parts that rely on accounts being a list from doCreateAccounts and doDepositAccounts into their own separate functions named properly.

**Comment by rwobben** [comment]
Oke, 

I think you mean this part in  doCreateAccounts. 

      let newBal      = read balStr :: Integer
          newAcct     = makeAccount newName newBal
          newAccounts = newAcct : accounts

expecially the part newAcct : accounts 

How do we call that ?

**Comment by GetContented** [comment]
Well, I usually ask myself "what is this function doing?"

In this case, it's adding an account to the accounts store.

    let newBal      = read balStr :: Integer
          newAcct     = makeAccount newName newBal
          newAccounts = addAccount newAcct accounts
      
    addAccount :: Account -> Accounts -> Accounts
    addAccount newAcct accounts = newAcct : accounts

**Comment by rwobben** [comment]
Oke, 

I deleted the one with IndexFilter on deleteAccount because we are going to work with a map.

Now I have doubt if the filter command works on a map. 
On the Data.Map I cannot find it out. Filter is on Prelude.

**Comment by rwobben** [comment]
I have also doubt about this one : 

    maybeAccountIdx s  = findIndex (isAccount s) 

And this one is already refractored out : 

       accountsAfterDeposit :: AccountStore -> Int -> Amount -> Description -> AccountStore
    accountsAfterDeposit accts idx amountToDeposit descriptionForDeposit = (take idx accts) ++   [depositedAccount] ++ drop (idx + 1) accts
      where depositedAccount = deposit amountToDeposit  descriptionForDeposit  (accts!!idx)

**Comment by rwobben** [comment]
I hope I have not forgot something ?

**Comment by GetContented** [comment]
Yeah, filter doesn't work on maps.

I'm very sorry. I always assume you understand what I mean whatever I say, which I really should not do, because it's very unlikely. We're different people.

Ok, so we're up to the step where we don't want to modify the functionality of any code, we only want to factor out all the functions that assume accounts is a list. We're doing this so we can collect all the places that relate to the accounts store as a List, and refactor them all at once. We're doing this to minimize the amount of changes we have to do between compiles. If we don't do this, we will end up with lots of errors we don't understand.

In other words, after we've made each change in this step, our code should still run, because we're only refactoring. Reactoring means changing the code without changing the way it works.

We need to go through each of our non-helper functions (the ones that return IO actions), and make sure none of them use list related stuff when dealing with the accounts store.

So, yes, filter only works on list types. You can see that if you do this at GHCi:

    > :t filter
    filter :: (a -> Bool) -> [a] -> [a]

You can see from its type it takes a predicate (function), and a List of "a". Map has its own functions for doing the various things we need to do.

You're also right in that the index-related code relates to List.

So, this step is about wrapping our accounts-related code in functions that name what those pieces of code are trying to do in a higher-level way.

I took this:

  let newBal      = read balStr :: Integer
      newAcct     = makeAccount newName newBal
      newAccounts = newAcct : accounts

... and changed it to this, by naming the functionality, by pulling it into its own named function.

    let newBal      = read balStr :: Integer
          newAcct     = makeAccount newName newBal
          newAccounts = addAccount newAcct accounts
      
    addAccount :: Account -> Accounts -> Accounts
    addAccount newAcct accounts = newAcct : accounts
    
... that way, when we come time to do the next step, which is writing versions of our functions that work with Map, we only have to look in the one place, and we will know the intent of the functions because they will be small, named and understandable.

If you look at the example above, in the first let expression, it's not easy at a glance to see what newAccounts is doing - you have to read the code. In the second let expression, though, it's obvious, because the name of the function tells us... oh... newAccounts is defined as adding newAcct to accounts. Ok. cool. I don't even need to look into the function definition for addAccount to see how it works. I can just assume that it does. This is sometimes called "blackboxing". Other times it's called encapsulation. It simply keeps things separate, and in this case we're separating out the reliance on List from that let expression. In the second case, there is *nothing at all* that says it relates to lists in any way. This is good, because it means that our code is not so reliant on the type of data accounts is in order to work with it.

**Comment by rwobben** [comment]
oke,
Then I try to refractor filter, findIndex  out of the functions
I think we are done with this step.  Right ?

**Comment by GetContented** [comment]
I haven't seen the code so I'm not sure.

**Comment by rwobben** [comment]
Solved by pr #19
