### ISSUE TITLE
change accounts to list 

### ISSUE THREAD

**Issue by rwobben** [rwobben/paytime#2]
Accounts are now still a int. 

We have to change it to this datastructure 

data Account = Account { accountNumber  :: Accountnumber
                               , accountname :: Accountname }

so we can have more then 1 account on our system

**Comment by GetContented** [comment]
If you do this, you'll be missing the "balance", which is what it currently is, so you should add that field, too. 
        accountBalance :: Integer

**Comment by rwobben** [comment]
oke, you mean the amount which is right now on that account. 
I can change that. Thanks for the tip

**Comment by rwobben** [comment]
One thing that pops into my mind,
As far as I know account is now 1 account like bank or cash on hands. 
If we make it a list can I then have both accounts with different balances and transactions ?

**Comment by GetContented** [comment]
You don't want to make Account a list, but rather have an accounts list per customer.  For now, seeing as you only have one customer, you wouldn't need anything more than a simple variable called `accounts` of type `[Account]`.

**Comment by rwobben** [comment]
oke, 

I was thinking about accounting accounts like bank or cash on hands. 
that was my Original idea. 
We could first look at multiple customers first

**Comment by GetContented** [comment]
Yes, I know what you were thinking. Be careful, you're increasing the complexity very quickly here.
There's a difference between an Account, and a list of accounts. There's nothing wrong with having a list of accounts per customer, but you don't want to put multiple accounts inside the Account data type. The Account data type describes a SINGLE account. You can then make multiple accounts from that data type.

Each customer can have a different list of accounts, and they can be of different types.

If you want to express the different types, perhaps you need an AccountType type.

    data AccountType = CheckingAccount | BankAccount | CashOnHandAccount

(etc.)

This is called a _sum type_, and it's part of the algebraic data types. The other is called a product type, and you've been using them all along (Transaction is an example of a product type).

**Comment by rwobben** [comment]
hmm, 

that means the accounts are fixed. 
that can be working on the short time but on the long run a user wants to use his /her own accounting accounts. 

Im afraid haskell is not the right tool for the job.

**Comment by GetContented** [comment]
No, Haskell is more than fine for this job. The problem is I'm not sure what you're meaning.

If I have an Account, I can name it  "My Cash Account" - that's its accountName. Its accountType would be something else - this would be the kinds of things the system will be able to do with it. For example, there might be a special saver account that attracts extra interest. Either way, you don't have to hardwire the properties into the account type if that's not what you want to do.

**Comment by rwobben** [comment]
Lets go back to we are a bank.
A customer can have multiple accounts like a account for paying bills and a saving account. 
Right now it seems to me that we have to make two seperate Accounts. 

What I want is  working to the accounting system I want to make. 
So the user can make and name accounting accounts as he/she wishes.

**Comment by GetContented** [comment]
Of course they could do that.
We specify that there's a type called Account... then the system can work with data whose type is Account.

You need a place to store these accounts, is all - and a list of them will work fine for now, though a Map would be better.

**Comment by rwobben** [comment]
Oke, a map is also fine.
Can you give a example how this looks like so I can figure out what needs to be changed in the code we have right now. 

We can start with for example 2 accounts.

**Comment by GetContented** [comment]
Ok. I see the problem you're worried about. You want to know how we can load and save data while using the system... we could use a file on disk, or a database.

If we don't persist the data, then all the data will be lost when you quit the program.

If you don't mind that, we can make a simple runloop that lets us create new accounts, and do deposits and withdrawls, and exit.

**Comment by rwobben** [comment]
at this stage , that is no problem.
Later just before we can convert it to a webapp we can add a database. 

First find out how things are working then we see later how we can achieve persitent. 

But I mean more this ; 

Does it look like this { (101, "first account" , 100) , ( 102, "second account" , 200) } or something else 

Roelof

**Comment by GetContented** [comment]
Sorry, I'm not sure what you're asking.

Does *what* look like that? The list of accounts? 

I don't know what syntax that is.

Maybe we should create a main runloop so you can see what happens.

The trouble with this, is I'm trying to introduce to as much Haskell as possible as we proceed, but in an order that won't confuse you, but also to consolidate and reinforce your knowledge. It's good to use real world examples such as this one we're using because they provide the passion and interest - they're exciting! :) And they're real.

However... if we start on the runloop, we'll need to know a lot of stuff that is not beginner Haskell, it's between intermediate and advanced. Either that, or we "temporarily treat it as magic".

Before we tackle IO actions, Monads and do notation, it's advisable to be already be able to use function application, currying, algebraic data types and typeclasses, and then be familiar with quite a few of the typeclasses (about 8 of them), and then be at least quite familiar with the following advanced Haskell: Semigroup and Monoid typeclasses, the Functor typeclass and the Applicative Functor typeclass.

If we skip ahead, and possibly if we treat the IO action as "magic", you may get confused and it'll make you disenchanted, and I don't want that to happen.

When I say "treat it like magic" I just mean work with it in a way where you don't understand it, you just know a little bit about how to use it.

As a quick example, I'll include a number guessing program... 
I'm happy to explain this program to you, and if we wrote a runloop for your accounting program as a temporary user interface, then it wold work quite similarly to doGuessing...

These *is* a lot of stuff going on here, though... and I don't want you to get scared by it.

    doGuessing :: Integer -> IO ()
    doGuessing num = do
       putStrLn "Enter your guess:"
       guess <- getLine
       if (read guess) < num
         then do putStrLn "Too low!"
                 doGuessing num
         else if (read guess) > num
                then do putStrLn "Too high!"
                        doGuessing num
                else do putStrLn "You Win!"

    main :: IO ()
    main = do
      putStrLn "Enter the secret number for your friend to guess"
      secret <- getLine
      doGuessing (read secret)

**Comment by GetContented** [comment]
Ideally, we proceed at a slow and steady pace through all these things until you're comfortable with them... by the time you are, you'll know enough Haskell to write any program you like, and to find out whatever else you don't know reasonably easily.

**Comment by rwobben** [comment]
That is what I also want. to learn and to understand things .
The number guesssing game does not scare me , At first glance I do understand it well.

**Comment by GetContented** [comment]
Sure. It's true that "do syntax" makes Monads easier to look at and understand what's going on, but they work differently than normal functions.

Normal functions in Haskell are just like in math: a mapping between a whole set of values (which is what a Type is) to another set of values (another Type).

However, a Monadic value is a single value that can be broken down into many pieces that fit together in a kind of structured, composed way. A good example is a List. The List [1,2,3] is actually a Monad value, because it's a single value, but you can look at it like it's composed of three pieces in an order and a wrappering.

Most programming languages behave in a monadic way. When you write a bunch of instructions in clojure, ruby or C, they are automatically sequenced together by the programming language in the order that you write them down in. The fact that Haskell doesn't behave like this all the time is usually what makes it tricky to think about.

Also, that's only ONE way out of many possible ways to sequence instructions together. Haskell can do this, of course, but it can also do a number of other different things that other languages just can't, because having the Monad as a typeclass in the language make the very structure of execution available as a programmable aspect of the language.

Ok, I'm pretty happy that if you aren't scared by the number guessing program you won't burn out and get scared or overwhelmed, so long as you realise it's only a partial understanding.

Also note that this is only ONE monad - the one for IO. Others behave differently. And, there's nothing about IO that means it *has* to be a Monad: they're separate ideas and concepts, it just happens that in Haskell, IO is a Monad because it's very convenient and useful.

IO () is a single type, albeit a composed one, and it's the type that the expression that is defined as main needs to be. When Haskell compiles a program it looks for the main function, and running it will evaluate and then execute that value, which should be of type IO (). That may involve further evaluation as needed.

Anyway :) Should be good either way.

**Comment by rwobben** [comment]
Thanks for the lesson

**Comment by GetContented** [comment]
Haha I hope it wasn't too annoying!

Let me know if you don't understand anything.

**Comment by rwobben** [comment]
I will do

**Comment by rwobben** [comment]
Yes. we can closed it because accounts is already a list.
