### ISSUE TITLE
Check if a account exist so we do not get double accounts

### ISSUE THREAD

**Issue by rwobben** [rwobben/paytime#20]
At this moment. it is possible to add a account two times.

We schould fix it so it will not happen

**Comment by GetContented** [comment]
It's actually not possible at the moment. What will happen is the old account will be wiped out (we're using Data.Map's insert function which overwrites a value if the key-value pair already exists).

So yes, we should check if the account exists before we make it, but not because we will get double accounts.

**Comment by rwobben** [comment]
oke, 

So we can check if a account already exist.
If not. then map insert can do the job
if  the account exist the user will get a error message

**Comment by GetContented** [comment]
Sounds good. :) Haha hey... look who's writing Haskell now with almost no help from me for some things! :)

**Comment by rwobben** [comment]
Meeeee.
