### ISSUE TITLE
make a withdrawl 

### ISSUE THREAD

**Issue by rwobben** [rwobben/paytime#23]
Now its time to make functions to take care that a user can withdrawl a amount from a account. 

This one is easy because it's almost simular from the deposit function. 

Maybe look to make a check that the amount cannot be lower then zero ? 
Or wait till a next challenge ?

**Comment by GetContented** [comment]
Sounds good. I'm pretty confident you can handle this easily, check and all.

**Comment by rwobben** [comment]
oke, 
Thanks for the confidence.

**Comment by GetContented** [comment]
Well it feels like you're starting to get the hang of Haskell basics, which is nice. Starting to understand that most of Haskell is understanding the types and matching them together.

There's still a lot to learn, but it's fine. Bit by bit :)

**Comment by rwobben** [comment]
I know I have a lot to learn. 
This one and the former one were easy because we did something that looks like it. 

I will work on this one the next few days.

**Comment by rwobben** [comment]
Hmm, if I use lookup for fetching the account , I get a maybe Account.  but I want only a account. 
Tommorrow I want to try if ! can do the job. We know the key, that one the user has given and we have already checked if it's exist.

**Comment by GetContented** [comment]
Yeah, better rather not to fetch the Account, but rather use adjust on the map. It's pretty much the same as the functionality in depositToAccountInStore.

**Comment by GetContented** [comment]
It might be that you're still thinking imperatively a bit.

If the function you're writing takes a List, and returns a List, you don't want to be pulling things out and doing things and putting them back if you can help it. Rather, you're better off using higher order functions to do your work: that is creating a new list that is based on the old one, but is slightly different.

In our case, we want to use Map.adjust, because it's an example of a higher order function. It takes a function, a key and a Map, and builds a new Map by using the same data except for running the adjustment function on the value at the key. :)

**Comment by rwobben** [comment]
So if I understand you right, I can use adjust to check if the account will be less then zero ? 
I had it almost working with a extra if then

**Comment by GetContented** [comment]
If all you want to do is silently fail, you can definitly use adjust to check if the account will be less than 0, however it's possibly better to handle this in the UI.

In other words, this depends where you want to check, and why.

If you want to tell the user, then you'll need to do the check in the UI function.

Otherwise, if you want it to be handled in the deposit function, what should it do if the program calls it in such a way that the account goes negative? Should it crash the program? (using the error function)? Should it silently fail? If not, then we will need to start to look into the Either type, which provides for being able to return errors in the response value in a similar fashion to Maybe does with Nothing, except that rather than a value such as Nothing, it's a more complicated value such that you can put a String on it.

However, the Either type is not a simple type, and I think for now we should just handle validation in the non-pure part of our code (the UI part).

If you're handling the error in the UI, the pure function will never be called with a withdrawl that takes the account into negative

**Comment by rwobben** [comment]
I wanted to tell the user . That is why I used a if then . 
The same idea as we did with the check if a account exist.

**Comment by GetContented** [comment]
Cool. Then it has nothing to do with the adjust function.

**Comment by rwobben** [comment]
oke, then I have made a PR to let you see how I solved it.

**Comment by rwobben** [comment]
closed by pr #25
