### ISSUE TITLE
input validation 

### ISSUE THREAD

**Issue by rwobben** [rwobben/paytime#24]
On this moment the programm will crash if someone will enter something else then a number in line 52 and 88. 

The solution would be some sort of validation.
if it's a number , continue
if it's not a number,  error message and go back to asking a number

**Comment by GetContented** [comment]
In the Text.Read module, there is a function readMaybe :: Read a => String -> Maybe a that should provide you with what you want.

**Comment by rwobben** [comment]
Thanks 

Is that one better then using the ! function in Data.Map

**Comment by rwobben** [comment]
I know, 
I will make a new branch and try to make this work.

**Comment by rwobben** [comment]
Here we have a problem. 

In add-account we do this ; 

let newBal      = read balStr :: Integer
            newAcct     = makeAccount newName newBal
            newAccounts = addAccount newAcct accts

I do not see how we can use ReadMaybe because we use the newBal direct on the rest of the functions.

Or we must use multiple lets. One for newbal and then a check , If it's succeed then the other two let so it continue. 

What do you think ?

**Comment by GetContented** [comment]
This depends what you want to do if they don't enter a number. Sure, we tell them it wasn't a number, but then what?

Do we want to exit out of creating the transaction entirely, or do we tell them it wasn't a number and then loop forever asking them for a number until they put one in?

They're quite different pieces of code.

**Comment by GetContented** [comment]
Here's the "infinite loop" one. Study this well... and maybe if you want the other one you can tackle it on your own (note I haven't typechecked this)

    doCreateAccounts :: AccountStore -> IO AccountStore
    doCreateAccounts accts = do
      putStrLn "Enter new account name"
      newName <- getLine
      if doesAccountExistInAccounts newName accts
      then do 
            putStrLn "Account already exist"
            return accts 
      else do 
            newBal <- getBalance
            let newAcct     = makeAccount newName newBal
                newAccounts = addAccount newAcct accts
            putStrLn $ "Account " ++ newName ++ " made with balance " ++ show newBal ++ "."
            return newAccounts

    getBalance :: IO (Integer)
    getBalance = do
      putStrLn "Enter new account balance"
      balStr <- getLine
      case readMaybe balStr of
      Just bal -> return bal
      Nothing -> do 
        putStrLn "That wasn't a number. Please try again."
        getBalance

**Comment by rwobben** [comment]
Thanks, 

I did not realize I  can use another function as argument for <- 

We could use this also for a non-exesting account but im happy as we do it now so I will not change that code

**Comment by rwobben** [comment]
One question : 

I see that getBalance has a type definition as :: IO Integer 
I always thought you have to mention the type of the input and the type of the output.
Or is that not needed when the types are the same ?

**Comment by GetContented** [comment]
Well, getBalance is not a function, it's an IO action. There is a difference in Haskell between executing and evaluating. Function application can be evaluated and answers worked out. These are mappings between input values and output values. If you give a function the same input, you'll always get the same output. That's what purity means when we say Haskell is a purely functional programming language.

IO does not work like this. The function (+3) is a function. It has type Num a => a -> a. If you give it 5, it will give you 8, which is a real value. However, getLine is not a function. It doesn't take values. It *is* an IO value. It's an executable value, and it's an executable value that can get a String and do something with it when composed with other executable values using monadic binding. 

The function putStrLn is only a function because it takes a String and returns an IO () value. When you give it the string "Hello", then that expression will be an IO () value at that point. It doesn't return any value other than that. You can't "get" the String out of it anymore, because the String doesn't exist any more - it's become part of the IO value. However, because it's in IO, you can execute it, and when you do, it will print the word "Hello" on the screen. Each time you execute it, it will do that.

When you hook IO actions together in a do block, like for example when you write this:

    do 
      name <- getLine
      putStrLn $ "Hi there, " ++ name

the type of that whole do block is IO (). Why? because do blocks BIND monadic actions together to form one single action. That's what they do.

I'll try not to confuse you too much, but when you write the above do block, this is what it ends up being turned into:

    getLine >>= (\name -> putStrLn $ "Hi there, " ++ name)

That (>>=) function connects the String that comes from getLine into the lambda (function) on the right. 

I hope this makes sense. If not, don't worry too much, but just think of IO actions as being a single value from Haskell's point of view, and do blocks as binding multiple actions into one single action.

You can use pure functions from within IO actions, but not the other way around.

And you can write do blocks in named expressions as IO values like I did above. If they return a type like IO Transaction, or IO String or IO Integer, then that means you can use them with <- in other IO actions just fine to kind of pull out the value (even though that's not actually what's happening - what's actually happening is you're just connecting pieces of the IO actions together so that Haskell knows how the IO actions fit together to form a single whole).

Let me know if you have questions. I tend to think of IO actions as being like a circuit. Connecting them together doesn't "do" anything and you can't see their result until you turn on the power (execute them), at which point, all the effects of the circuit board become apparent.

**Comment by rwobben** [comment]
it clear I think.
If you are happy  I will merge this one and try to solve the next challenge.

**Comment by GetContented** [comment]
Nicely done.

**Comment by rwobben** [comment]
Solved #26
