### ISSUE TITLE
refractor the code in different libs

### ISSUE THREAD

**Issue by rwobben** [rwobben/paytime#30]
Because lib.hs is becomming bigger and bigger I think it's the best to make seperate libs for accounts. transactions and reports.

**Comment by rwobben** [comment]
First I think we can refractor the menu so it has submenu's. 

I think of this layout 

Accounts  
    *  Create 
    *  Delete 

Transaction 
    * deposit 
    * withdrawl 

Reports 
  *  Total balance 
  *  Transaction by account.

**Comment by rwobben** [comment]
I have a problem with rewriting it in submenus. 

So far I have this :  http://lpaste.net/149772

If I change the submenu to IO() -> String  I see a error message on the submenu_accounts function
When I change it to  IO -> IO String. I see a error message on the case statement. 

How to solve this without making very big functions.

**Comment by GetContented** [comment]
Ok.

Seeing as you're working with IO, you should know how it works.

Once you're "IN" IO, you can't get out of it.

So, it's actually impossible to have a function that goes from IO to something not in IO. "Once you're in IO, you're stuck in IO".

So, your type for the submenu function has to return IO String.

A case expression takes a value. IO String is not String, and you can't "pull the string out of IO" by pattern matching. The only way you can "pull the string out" so to speak, is to use <-. Note that this is not actually pulling anything out of anywhere. What it's doing is hooking the IO action's return value up to your function.

So, the result of "CA" -> need to be a do block:

    do
      submenuResp <- subMenu_accounts
      case submenuResp of...

(and continue with what you had before).

**Comment by GetContented** [comment]
I think you should pull out all the pure functions that are about the core functionality into their own Module... and put all the code that has to do with the UI (all the IO returning functions) into another Module.

**Comment by rwobben** [comment]
I do not get it in total. 
How would you do this . one for all the functions and one for the reports ?

**Comment by GetContented** [comment]
Lib should have the pure functions in it (not IO)

Another file should have the IO functions in it.

Do you get that?

**Comment by rwobben** [comment]
oke, 

So one with the pure functions and one with all the input things. 
How do we call them. Lib.hs and input.hs ?

**Comment by GetContented** [comment]
I'm not sure. You should probably name your file the same as your module, though, so I think that means it'll need to start with a capital.

**Comment by rwobben** [comment]
Oke, Lib.hs and Input.hs . 
If you know better ways im open for it.

**Comment by rwobben** [comment]
I asked a few people on haskell irc channel and most of them said if I want to seperate things. 
Make a seperate modules named paytime.accounts and paytime.transactions. 
And put all the "reports" on the same module.

**Comment by GetContented** [comment]
Yeah, the most basic separation you could do is what I suggested. You can happily do more.

However, the pure functions need to be separated from the UI code in my opinion, because our codebase is going to be serving two different UIs (one web, one command line), and if you have them together, it might be annoying that your commandline UI code is mixed in with your pure functions.

Do what you like at the end of the day because you're the one learning this, and whatever you decide needs to be your decision because that's what you'll learn from. I'm only talking from my experience.

The reasons to separate things out are:

1. It's easier to think about smaller sets of code than larger ones.
2. It's good to have logically similar things grouped together so you can import them in the module size you need (not too many or too few imports).

But like I said, you'll learn best from mistakes you make yourself. Me "helping" you here by imposing a way of doing things is not going to help you.

**Comment by rwobben** [comment]
Oke, first we seperate things out and we see what to do next.

But first I want to make work the layout I have in my head. 
I found some outside libraries that could do the job but they work with array and we works with map.
And I do not think it's wise to use maps for storage and put the same data in array so we can print.
it's looks double to me. 

Roelof

**Comment by GetContented** [comment]
I think you mean lists, not arrays.

There's no particular problem with using Data.Map's elems function. It's subject to list fusion, so it'll be efficient, so long as you don't have stupendously large numbers of accounts.

**Comment by rwobben** [comment]
one "problem "  I have to think about.
Im now working on Make a transaction" 
And I want to display the new balance value of that account when a user has made a deposit. 

What I have to figure out is how to get that value.
I have all accounts (accts) . I know which account we want a deposit on (AccountToDeposit) 
So I think I need something like a lookup to pull the right accounts out of the map and then use AccountBalance function to take the old value out of the account. 

Am I on the right track ?

**Comment by GetContented** [comment]
I thought the code already worked.

Are you still talking about refactoring to different modules? This won't involve rewriting anything other than a few imports.

**Comment by GetContented** [comment]
Oh ok this is not about THIS issue then.

If I was writing it, I'd make the deposit, defining a temporary variable as the resultant AccountStore, then use that to get the current balance out of the account using something like:

    getAccountBalance :: String -> AccountsStore -> Amount
    getAccountBalance accountName = accountBalance . (! accountName)

and then do your printing with that value, then use the temporary account store variable as the result of the whole operation (looping back etc.)

**Comment by rwobben** [comment]
yes . I want to make the output of deposit also like a table. 

I think that code will not work. 
You said to use a String and a AccountStore and I do not see a AccountStore.

Maybe something like this : 

    getAccountBalance :: String -> AccountStore -> Amount
    getAccountBalance accountName  accts = accountBalance . (! accountName accts)

**Comment by GetContented** [comment]
Your code is wrong.

Mine should work fine.

    getAccountBalance :: String -> AccountStore -> Amount
    getAccountBalance accountName = accountBalance . (! accountName)

What's happening there is it's an eta-reduced function of 2 arguments. getAccountBalance is a function of String and Map. The Map has type Map String Account, and so the (!) function takes the map and an account name. We're using a section (! accountName) to make a one-argument function that takes a map and returns an Account, and we have function composition with the accountBalance function which takes an account and returns an Amount. It should work fine. Add the extra arguments if you're comfortable, but add them in the right place, or use function application instead of composition:

    getAccountBalance :: String -> AccountStore -> Amount
    getAccountBalance accountName  accts store = accountBalance $ store ! accountName accts

    getAccountBalance :: String -> AccountStore -> Amount
    getAccountBalance accountName  accts store = accountBalance . (! accountName accts) $ store

**Comment by rwobben** [comment]
I managed it another way. if you aprove my PR , then we can work on or making transactions work or first refractor all IO stuff out of the Lib,hs

**Comment by GetContented** [comment]
I already said it looks fine to me yesterday, I think.

**Comment by rwobben** [comment]
I did make new commits today that is why I asked

**Comment by GetContented** [comment]
oh hang on I'll look again.
