### ISSUE TITLE
 adjust the types so that they are data types

### ISSUE THREAD

**Issue by rwobben** [rwobben/paytime#8]
We now uses types. 
Maybe better to convert all types to data types ?

**Comment by rwobben** [comment]
When I change the type to this : 

    data Amount = Amount Integer
    data Account = Account Integer
    data Description = Description String 
    data Transaction = Transaction { transactionAmount :: Amount
                               , transactionDescription :: Description}

Then I see this error message : 

    /home/ubuntu/workspace/paytime/paytime/src/Lib.hs:13:50:
        Couldn't match expected type ‘Account’ with actual type ‘Amount’
        In the second argument of ‘(+)’, namely
          ‘transactionAmount transaction’
        In the expression: account + transactionAmount transaction

on this line 

    applyTransaction transaction account = account + transactionAmount transaction

**Comment by GetContented** [comment]
Two things

1. I don't think you should change the type of Amount to its own special data type. It's just going to stay a number, isn't it?

2. You need to adjust applyTransaction if you're going to change the type of Account. Because of the way we've made deposit and withdraw rely on applyTransaction now, you only have to change it in this one place.

These are the new types:

    type Amount = Integer
    type Description = String

    data Account = Account { accountAmount :: Amount }
    data Transaction = Transaction { transactionAmount :: Amount
                                   , transactionDescription :: Description}

and this is the changed applyTransaction function:

    applyTransaction :: Transaction -> Account -> Account
    applyTransaction transaction account = Account {accountAmount = newAccountAmount}
      where newAccountAmount = accountAmount account + transactionAmount transaction

I'm assuming you remember that a where clause introduces locally scoped definitions, and this one for newAccountAmount uses the accountAmount function to pull the value out of the Account, and the transactionAmount to pull the value out of the Transaction.

What about Account {accountAmount = newAccountAmount} ? That's just a non-positional record seletor way to make an Account. Here it's identical to Account newAccountAmount. We use the *value constructor* Account to create a new Account.

If anything's not clear, just let me know and I'll try to explain.

Do you see how we have to adjust *all* the pieces of code that rely on the *shape* of the data types when we change the shape of the data types?

It'd important to know what relies on what when you write code. To write clean, simple, clear code, it's good to keep the things that rely or depend on other things to a minimum if possible, that way when you change something, you don't have so much to change.

Imagine we made this change to Account, and we still had the destructuring in place on withdraw and deposit? Then we'd need to change *them* as well!

**Comment by rwobben** [comment]
Oke, 

Then I misunderstood the exercise. 

I think I understand the things you try to learn me.

**Comment by rwobben** [comment]
one question pops into my mind. 

Why here this ;  

    accountAmount account + transactionAmount transaction

to be more specific ; why are account and transaction mentioned here.

**Comment by GetContented** [comment]
Well, when we setup the Account as a record, Haskell creates functions to get each of the fields data out of an Account, which is quite nice.

So, when we wrote data Account = Account { accountAmount :: Amount }, haskell creates an accountAmount function whose type is accountAmount :: Account -> Amount and of course, when we declare the data type, it creates a value constructor function for Account too, whose type is Account :: Amount -> Account . This is how we create new Account values.

So that line you referenced is taking the passed in Account value, and getting the Amount value out of it with the accountAmount function, then taking the transaction passed in, and getting its Amount value out of it with the transactionAmount function, then adding them together with the (+) function.

Does that make sense?

**Comment by rwobben** [comment]
this make sense

**Comment by rwobben** [comment]
If you have time , could you look if my pr is well and can be committed

**Comment by GetContented** [comment]
I did. I think it's good. My only comment might be that perhaps instead of accountAmount, maybe it should be named accountBalance ? Up to you, though. (If you do change it, don't forget to update it everywhere obviously)

**Comment by rwobben** [comment]
oke, I will change it and commit it. 
Another isssue ready :) . Up to the next in line.
